project:
  type: website
  output-dir: docs

website:
  title: "Data Analysis Portfolio"
  site-url: https://analyses.anthony.computer
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - href: index.qmd
  #       text: Home
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Home
      - section: "Analyses"
        contents:
          - tidy_tuesday_nyc_elevators/tidy_tuesday_nyc_elevators.qmd
          - septa_transit_times/septa-timetables.qmd
      - section: "More from Anthony"
        contents:
          - href: https://anthony.computer
            text: anthony.computer
          - href: https://www.linkedin.com/in/awbaker1/
            text: LinkedIn
          - href: https://anthony.computer/BakerResume_v19.3_data.pdf
            text: Resume
          - href: "mailto:anthonywbaker1@gmail.com"
            text: Contact